FROM ruby:3.0-alpine3.13

ENV APP_PATH /project
ENV APP_BIN_PATH "$APP_PATH/bin"
ENV PATH "$PATH:$APP_BIN_PATH"

WORKDIR $APP_PATH

COPY ./bin/install_system_dependencies $APP_BIN_PATH/install_system_dependencies
RUN install_system_dependencies

# RUBY ENVS
ENV BUNDLE_PATH "${APP_PATH}/vendor/bundle"
ENV BUNDLE_BIN "${BUNDLE_PATH}/ruby/2.7.0/bin"
ENV PATH "${PATH}:${BUNDLE_BIN}"
ENV BUNDLE_JOBS 4

USER user

ENTRYPOINT [ "entrypoint" ]